version: 2

models:
  - name: restaurant_division
    columns:
      - name: client_id
        tests:
          - not_null
      - name: name
        tests:
          - not_null
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: dev.restaurant_division_age