version: 2

models:
  - name: restaurant_division_info_view
    columns:
      - name: client_id
        tests:
          - not_null
      - name: name
        tests:
          - not_null

    
  - name: restaurant_info
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('restaurant_info_raw')

  - name : age_view
    columns:
    - name : age
      tests:
        - not_null
        
  
