
version: 2

models:
  - name: restaurant_division_info_view
    description: "Restaurant Informations"
    columns:
      - name: client_id
        tests:
          - not_null
      - name: name
        tests:
          - not_null
      - name: latitude
        tests:
          - dbt_utils.acccepted_range:
              min_value : -90
              max_value : 90
              inclusive : true
      - name: longitude
        tests:
          - dbt_utils.acccepted_range:
              min_value : -180
              max_value : 180
              inclusive : true

  - name : age_of_restro_after_registration
    columns:
    - name : age
      tests:
        - not_null
        
          

